name: AdBlock Filter Compiler

on:
  schedule:
    - cron: '0 18 * * *' # Runs every day at 1 PM EST (6 PM UTC)
  workflow_dispatch:

jobs:
  generate_adblock_filters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Run filter generator script
      run: python adblock_filter_compiler.py

    - name: Commit and push updated filter list
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add blocklist.txt
        git commit -m "Update filter list" || echo "No changes to commit"
        git push
